Repository peacefulcraft-network/Borough, pull requests merged in 2021-12, with the labels that each got.

#8 Claiming mechanics
  src/net/peacefulcraft/borough/utilities/EntityHandler.java
Labels: project

#10 Update PlayerCacheEventListeners.java
  src/net/peacefulcraft/borough/listeners/PlayerCacheEventListeners.java
Labels: bug

#11 Feat/better caching
  src/net/peacefulcraft/borough/commands/ClaimCommand.java
  src/net/peacefulcraft/borough/storage/BoroughChunk.java
  src/net/peacefulcraft/borough/storage/BoroughClaim.java
  src/net/peacefulcraft/borough/storage/BoroughClaimStore.java
  src/net/peacefulcraft/borough/storage/SQLQueries.java
  src/net/peacefulcraft/borough/storage/UUIDCache.java
Labels: bug

#21 Update PlayerMovementListener.java
  src/net/peacefulcraft/borough/listeners/PlayerMovementListener.java
Labels: bug

#22 Update PlayerCacheEventListeners.java
  src/net/peacefulcraft/borough/listeners/PlayerCacheEventListeners.java
Labels: enhancement
